### PR TITLE
Rename `invalid_mut` to `without_provenance_mut`

### PR DESCRIPTION
**Pull request by rice7th**
Plain rename made for newer nightlies.

Fixes https://github.com/sunfishcode/c-ward/pull/122 too.

### CODE REVIEW

**Comment by sunfishcode** [comment]
Thanks! Could you also update rust-toolchain.toml to point to a nightly version that has the new names, and run `cargo fmt`?

**Comment by rice7th** [comment]
Sure! Just give me around six hours when I am back from school.

**Comment by rice7th** [comment]
@sunfishcode Done, for both PRs. If you encounter any problems caused by the version bump, please let me know!

**Comment by rice7th** [comment]
EDIT: I am trying to fix all CI errors, but each time a new one pops out. It may require a bit of time to prepare the PR correctly.

**Comment by sunfishcode** [comment]
This is now released in origin 0.18.0.

**Comment by rice7th** [comment]
Absolutely no problem! Glad I can help for this awesome project =)

**Pull request merged**
